# Import Libaries

In [1]:
import numpy as np
import pandas as pd

# Importing Data

In [2]:
crop = pd.read_csv("Crop_recommendation.csv")
crop.head()

N   P   K  temperature   humidity        ph    rainfall label
0  90  42  43    20.879744  82.002744  6.502985  202.935536  rice
1  85  58  41    21.770462  80.319644  7.038096  226.655537  rice
2  60  55  44    23.004459  82.320763  7.840207  263.964248  rice
3  74  35  40    26.491096  80.158363  6.980401  242.864034  rice
4  78  42  42    20.130175  81.604873  7.628473  262.717340  rice

# Asq Six Question to yourself

In [3]:
crop.shape

(2240, 8)

In [4]:
crop.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2240 entries, 0 to 2239
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   N            2240 non-null   int64  
 1   P            2240 non-null   int64  
 2   K            2240 non-null   int64  
 3   temperature  2240 non-null   float64
 4   humidity     2240 non-null   float64
 5   ph           2240 non-null   float64
 6   rainfall     2240 non-null   float64
 7   label        2240 non-null   object 
dtypes: float64(4), int64(3), object(1)
memory usage: 140.1+ KB


In [5]:
crop.isnull().sum()

N              0
P              0
K              0
temperature    0
humidity       0
ph             0
rainfall       0
label          0
dtype: int64

In [6]:
crop.duplicated().sum()

0

In [7]:
crop.describe()

N            P            K  temperature     humidity  \
count  2240.000000  2240.000000  2240.000000  2240.000000  2240.000000   
mean     50.858036    53.269196    47.863839    25.572512    70.938855   
std      36.839323    32.718573    50.250527     5.077273    22.437972   
min       0.000000     5.000000     5.000000     8.825675    14.258040   
25%      21.000000    28.750000    20.000000    22.697495    58.588306   
50%      37.000000    51.000000    32.000000    25.550002    80.282849   
75%      85.000000    68.000000    48.000000    28.550191    89.806711   
max     140.000000   145.000000   205.000000    43.675493    99.981876   

                ph     rainfall  
count  2240.000000  2240.000000  
mean      6.476815   101.699662  
std       0.770677    56.021019  
min       3.504752     0.000000  
25%       5.981027    63.270019  
50%       6.433125    93.774350  
75%       6.928163   122.567888  
max       9.935091   298.560117

In [8]:
crop['label'].value_counts()

chickpea       110
rice           100
maize          100
coffee         100
jute           100
cotton         100
coconut        100
papaya         100
orange         100
apple          100
muskmelon      100
watermelon     100
grapes         100
mango          100
banana         100
pomegranate    100
lentil         100
blackgram      100
mungbean       100
mothbeans      100
pigeonpeas     100
kidneybeans    100
wheat           10
jowar           10
mustard         10
Name: label, dtype: int64

# Encoding

In [9]:
crop_dict = {
    'rice': 1,
    'maize': 2,
    'jute': 3,
    'cotton': 4,
    'coconut': 5,
    'papaya': 6,
    'orange': 7,
    'apple': 8,
    'muskmelon': 9,
    'watermelon': 10,
    'grapes': 11,
    'mango': 12,
    'banana': 13,
    'pomegranate': 14,
    'lentil': 15,
    'blackgram': 16,
    'mungbean': 17,
    'mothbeans': 18,
    'pigeonpeas': 19,
    'kidneybeans': 20,
    'chickpea': 21,
    'coffee': 22
}
crop['crop_num']=  crop['label'].map(crop_dict)

In [10]:
crop.dropna(inplace=True)

In [11]:
crop.drop(['label'],axis=1,inplace=True)
crop.head()

N   P   K  temperature   humidity        ph    rainfall  crop_num
0  90  42  43    20.879744  82.002744  6.502985  202.935536       1.0
1  85  58  41    21.770462  80.319644  7.038096  226.655537       1.0
2  60  55  44    23.004459  82.320763  7.840207  263.964248       1.0
3  74  35  40    26.491096  80.158363  6.980401  242.864034       1.0
4  78  42  42    20.130175  81.604873  7.628473  262.717340       1.0

# Train Test Split

In [12]:
X = crop.drop(['crop_num'],axis=1)
y = crop['crop_num']

In [13]:
X

N   P   K  temperature   humidity        ph    rainfall
0     90  42  43    20.879744  82.002744  6.502985  202.935536
1     85  58  41    21.770462  80.319644  7.038096  226.655537
2     60  55  44    23.004459  82.320763  7.840207  263.964248
3     74  35  40    26.491096  80.158363  6.980401  242.864034
4     78  42  42    20.130175  81.604873  7.628473  262.717340
...   ..  ..  ..          ...        ...       ...         ...
2230  32  58  21    19.120000  36.120000  6.950000    0.000000
2231  41  61  27    22.120000  39.120000  7.120000   11.100000
2232  37  55  19    17.120000  31.120000  6.880000    0.000000
2233  44  65  25    24.120000  41.120000  7.220000   15.100000
2234  31  50  17    21.450000  33.120000  6.750000    0.000000

[2210 rows x 7 columns]

In [14]:
y

0        1.0
1        1.0
2        1.0
3        1.0
4        1.0
        ... 
2230    21.0
2231    21.0
2232    21.0
2233    21.0
2234    21.0
Name: crop_num, Length: 2210, dtype: float64

In [15]:
y.shape

(2210,)

In [16]:
from sklearn.model_selection import train_test_split

c:\Users\thora\anaconda3\lib\site-packages\scipy\__init__.py:155: UserWarning: A NumPy version >=1.18.5 and <1.25.0 is required for this version of SciPy (detected version 1.26.4
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"


In [17]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [18]:
X_train

N    P    K  temperature   humidity        ph    rainfall
841    16   65   19    27.612050  69.297862  7.043160   42.723744
1975  134   56   18    23.808346  83.919026  6.691268   70.973583
798    44   77   21    32.639187  61.300905  7.326980   61.838761
1234   20  142  196    10.898759  80.016394  6.207601   68.694204
1362  111    6   53    26.493065  88.591431  6.313513   46.063822
...   ...  ...  ...          ...        ...       ...         ...
1638   10    5    5    21.213070  91.353492  7.817846  112.983436
1095  108   94   47    27.359116  84.546250  6.387431   90.812505
1130   11   36   31    27.920633  51.779659  6.475449  100.258567
1294   11  124  204    13.429886  80.066340  6.361141   71.400430
860    32   78   22    23.970814  62.355576  7.007038   53.409060

[1768 rows x 7 columns]

In [19]:
y_train

841     15.0
1975     4.0
798     16.0
1234    11.0
1362    10.0
        ... 
1638     7.0
1095    13.0
1130    12.0
1294    11.0
860     15.0
Name: crop_num, Length: 1768, dtype: float64


# Scale the features using MinMaxScaler

In [20]:
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import StandardScaler
ms = MinMaxScaler()
sc = StandardScaler()

X_train = ms.fit_transform(X_train)
X_test = ms.transform(X_test)

X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)




In [21]:
X_train

array([[-0.93704902,  0.36607117, -0.56857831, ..., -0.10264078,
         0.72336571, -1.08775196],
       [ 2.28175618,  0.09286989, -0.58857088, ...,  0.55898813,
         0.26866807, -0.5813056 ],
       [-0.17326474,  0.73033955, -0.52859317, ..., -0.46451472,
         1.09010418, -0.74506927],
       ...,
       [-1.07343907, -0.51424407, -0.32866746, ..., -0.89536494,
        -0.01020231, -0.05630177],
       [-1.07343907,  2.15705735,  3.13004729, ...,  0.38464847,
        -0.15790574, -0.57365334],
       [-0.50060086,  0.76069525, -0.5086006 , ..., -0.41678935,
         0.67668971, -0.89619194]])

In [22]:
X_test

array([[-1.10071708,  0.79105094, -0.54858574, ..., -0.21135529,
        -0.1336904 , -1.16860525],
       [-0.52787887,  2.33919154,  3.01009187, ...,  0.95789963,
        -1.19978946,  0.29866267],
       [ 1.19063577, -1.4552707 ,  0.15115424, ...,  0.91978441,
        -0.51383995, -1.37172241],
       ...,
       [ 1.70891797, -0.48388837, -0.54858574, ...,  0.33837196,
         1.17598142, -0.11291109],
       [ 1.32702582,  0.06251419, -0.24869718, ...,  0.39246112,
         0.0237147 ,  3.12947106],
       [ 0.4541295 , -0.24104278, -0.18871947, ...,  0.47987329,
         1.05577223,  2.82335856]])

# Training Models

In [23]:
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.tree import ExtraTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import BaggingClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.metrics import accuracy_score,confusion_matrix

# create instances of all models
models = {
    'Logistic Regression': LogisticRegression(),
    'Naive Bayes': GaussianNB(),
    'Support Vector Machine': SVC(),
    'K-Nearest Neighbors': KNeighborsClassifier(),
    'Decision Tree': DecisionTreeClassifier(),
    'Random Forest': RandomForestClassifier(),
    'Bagging': BaggingClassifier(),
    'AdaBoost': AdaBoostClassifier(),
    'Gradient Boosting': GradientBoostingClassifier(),
    'Extra Trees': ExtraTreeClassifier(),
}


for name, model in models.items():
    model.fit(X_train,y_train)
    ypred = model.predict(X_test)
    
    print(f"{name}  with accuracy : {accuracy_score(y_test,ypred)}")
    print("Confusion matrix : ",confusion_matrix(y_test,ypred))
    print("==========================================================")
    

Logistic Regression  with accuracy : 0.9592760180995475
Confusion matrix :  [[15  0  4  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0 21  0  1  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0 19  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0 28  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0 15  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 1  0  1  0  0 23  0  0  1  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0 14  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0 25  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0 20  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0 18  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0 19  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0 22  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0 17  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  

In [24]:
# finally selected randomforest model

rfc = RandomForestClassifier()
rfc.fit(X_train,y_train)
ypred = rfc.predict(X_test)
accuracy_score(y_test,ypred)

0.9932126696832579

In [25]:
# or gausianjb
gnb = GaussianNB()
gnb.fit(X_train,y_train)
ypred = gnb.predict(X_test)
accuracy_score(y_test,ypred)

0.995475113122172

# Predictive System

In [26]:
def recommendation(N,P,k,temperature,humidity,ph,rainfal):
    features = np.array([[N,P,k,temperature,humidity,ph,rainfal]])
    transformed_features = ms.fit_transform(features)
    prediction = rfc.predict(transformed_features)
    return prediction[0] 
    print(prediction[0])

In [27]:
# new inputs

						
N = 17
P = 16
k = 14
temperature = 16.396243
humidity = 92.181519
ph = 6.625539
rainfall = 102.944161

predict = recommendation(N,P,k,temperature,humidity,ph,rainfall)

crop_dict = {1: "Rice", 2: "Maize", 3: "Jute", 4: "Cotton", 5: "Coconut", 6: "Papaya", 7: "Orange",
                 8: "Apple", 9: "Muskmelon", 10: "Watermelon", 11: "Grapes", 12: "Mango", 13: "Banana",
                 14: "Pomegranate", 15: "Lentil", 16: "Blackgram", 17: "Mungbean", 18: "Mothbeans",
                 19: "Pigeonpeas", 20: "Kidneybeans", 21: "Chickpea", 22: "Coffee"}

if predict in crop_dict:
    crop = crop_dict[predict]
    print("{} is a best crop to be cultivated ".format(crop))
else:
    print("Sorry are not able to recommend a proper crop for this environment")

Papaya is a best crop to be cultivated 


In [28]:
# new inputs 2


N = 100
P = 90
k = 100
temperature = 50.0
humidity = 90.0
ph = 100
rainfall = 202.0

predict = recommendation(N,P,k,temperature,humidity,ph,rainfall)

crop_dict = {1: "Rice", 2: "Maize", 3: "Jute", 4: "Cotton", 5: "Coconut", 6: "Papaya", 7: "Orange",
                 8: "Apple", 9: "Muskmelon", 10: "Watermelon", 11: "Grapes", 12: "Mango", 13: "Banana",
                 14: "Pomegranate", 15: "Lentil", 16: "Blackgram", 17: "Mungbean", 18: "Mothbeans",
                 19: "Pigeonpeas", 20: "Kidneybeans", 21: "Chickpea", 22: "Coffee"}

if predict in crop_dict:
    crop = crop_dict[predict]
    print("{} is a best crop to be cultivated ".format(crop))
else:
    print("Sorry are not able to recommend a proper crop for this environment")

Papaya is a best crop to be cultivated 


In [29]:
# new inputs 2
# ,,41,20.12,44.12,6.52,0.0
N = 107
P = 54
k = 41
temperature = 20.12
humidity = 44.12
ph = 6.52
rainfall = 0.0

predict = recommendation(N,P,k,temperature,humidity,ph,rainfall)

crop_dict = {1: "Rice", 2: "Maize", 3: "Jute", 4: "Cotton", 5: "Coconut", 6: "Papaya", 7: "Orange",
                 8: "Apple", 9: "Muskmelon", 10: "Watermelon", 11: "Grapes", 12: "Mango", 13: "Banana",
                 14: "Pomegranate", 15: "Lentil", 16: "Blackgram", 17: "Mungbean", 18: "Mothbeans",
                 19: "Pigeonpeas", 20: "Kidneybeans", 21: "Chickpea", 22: "Coffee"}

if predict in crop_dict:
    crop = crop_dict[predict]
    print("{} is a best crop to be cultivated ".format(crop))
else:
    print("Sorry are not able to recommend a proper crop for this environment")

Papaya is a best crop to be cultivated 


In [30]:
import pickle
pickle.dump(rfc,open('model.pkl','wb'))
pickle.dump(ms,open('minmaxscaler.pkl','wb'))
pickle.dump(sc, open('standscaler.pkl', 'wb'))